### ISSUE TITLE
Achievements Don't Show

### ISSUE THREAD

**Issue by GrimTheDragonLord** [8bitjake/PsychEngine-Lua-Achievements#1]
Hey! I've been waiting for something like this for a LONG time. Sadly though when I put the entire mod into my MODS folder for psych (PsychEngine/Mods) the awards song doesn't do anything. I go to freeplay and hit awards and everything shows except the achievements. I went into the code and saw it was also supposed to play music which that isn't working either. Sorry to be a bother!

**Comment by 8bitjake** [comment]
you have to put the mod into its _own_ folder, not in the base mods folder.
so everything has to be in, say, PsychEngine/mods/awards.

i tested this out by extracting the mod into the base folder, and it fits your description to a T.

just in case, make sure you're running psych engine v0.6.1 or later, as that is required for this to work.

hope this helps!
