### ISSUE TITLE
Large achievement list

### ISSUE THREAD

**Issue by Draconic-Hybrid** [8bitjake/PsychEngine-Lua-Achievements#4]
I've got a huge achievement list for my mod, and the icons go off-screen. Is there a way to add implementation for a thing where the awards menu scrolls down?

**Comment by 8bitjake** [comment]
can you send a screenshot of the achievement menu?

**Comment by Draconic-Hybrid** [comment]
![Friday Night Funkin'_ Psych Engine 11_4_2022 5_12_05 PM](https://user-images.githubusercontent.com/101238648/200091720-7c3ec8e2-9b54-41e8-90b8-da9389b9e4dc.png)

I think it might be worth noting that they only show up when I put them in mods/awards/achievements/achievements.txt instead of mods/[my mod]/achievements/achievements.txt
