### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by Draconic-Hybrid** [8bitjake/PsychEngine-Lua-Achievements#5]
Contrary to what is written in the documentation, the custom achievements only show up for me if I add my achievements into mods/awards/achievements/achievements.txt, and not mods/[mod]/achievements/achievements.txt.

I'm not sure if they're connected, but I also cannot unlock any of my achievements with the code provided.

I've even deleted the mods/[mod]/achievements folder, and they show up when in mods/awards/achievements

**Comment by 8bitjake** [comment]
the way the system loads mods is genuinely shit, working on a new system rn
for now you'll have to wait, sorry man/woman/person/whatever you go by

**Comment by Draconic-Hybrid** [comment]
Alright, thanks for confirming
