### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Draconic-Hybrid** [8bitjake/PsychEngine-Lua-Achievements#6]
So I managed to get it working by putting it in my mod's folder and changing up a few things in the code. Even fixed the achievement list problem. Now I'm wondering if there's a way to reset achievements. Is there? It's perfectly fine if there isn't btw

**Comment by 8bitjake** [comment]
there isnt
also can you make a PR for the achievement list fix (along with an example)? i want to put it in the actual system
